# Generated by Django 5.2.9 on 2026-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Designation', models.CharField(max_length=100, null=True)),
                ('Basic_salary', models.FloatField(null=True)),
                ('HAR_percent', models.FloatField(null=True)),
                ('DA_percent', models.FloatField(null=True)),
                ('TA_percent', models.FloatField(null=True)),
                ('Bonus', models.FloatField(default=0, null=True)),
                ('Overtime_hours', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
