# Generated by Django 5.2.9 on 2026-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='gross_salary',
            field=models.IntegerField(null=True),
        ),
    ]
