# Generated by Django 5.2.9 on 2026-01-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0002_employee_model_gross_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='Picture',
            field=models.ImageField(null=True, upload_to='Picture'),
        ),
    ]
